/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("buildlogic.kotlin-application-conventions")
}

dependencies {
  implementation(project(":axs"))
}

application {
  mainClass = "dev.pgaxis.axs.cli.MainKt"
  applicationName = "axs"
}

tasks.named<Jar>("jar") {
  archiveBaseName = "axs-lib"
}

tasks.register<JavaExec>("axsTests") {
  group = "verification"
  description = "Runs the AxsFile crash-safety/regression test harness"
  classpath = sourceSets["main"].runtimeClasspath
  mainClass.set("dev.pgaxis.axs.tests.AxsTestHarnessKt")
  args = listOf(project.findProperty("axsTestArgs") as? String ?: "all")
}
