/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("buildlogic.kotlin-application-conventions")
}

dependencies {
  implementation(project(":axs"))
}

application {
  mainClass = "dev.pgaxis.axs.cli.MainKt"
  applicationName = "axs"
}

tasks.named<Jar>("jar") {
  archiveBaseName = "axs-lib"
}
